# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog_date.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_date_window(object):
    def setupUi(self, date_window):
        date_window.setObjectName("date_window")
        date_window.resize(421, 400)
        self.gridLayout = QtWidgets.QGridLayout(date_window)
        self.gridLayout.setObjectName("gridLayout")
        self.keyword_label = QtWidgets.QLabel(date_window)
        self.keyword_label.setStyleSheet("font: 11pt \"Helvetica\";")
        self.keyword_label.setObjectName("keyword_label")
        self.gridLayout.addWidget(self.keyword_label, 0, 0, 1, 2)
        self.date_label = QtWidgets.QLabel(date_window)
        self.date_label.setObjectName("date_label")
        self.gridLayout.addWidget(self.date_label, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(date_window)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 3)
        self.label = QtWidgets.QLabel(date_window)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.select_btn = QtWidgets.QPushButton(date_window)
        self.select_btn.setObjectName("select_btn")
        self.gridLayout.addWidget(self.select_btn, 2, 1, 1, 1)
        self.clear_btn = QtWidgets.QPushButton(date_window)
        self.clear_btn.setObjectName("clear_btn")
        self.gridLayout.addWidget(self.clear_btn, 2, 2, 1, 1)
        self.DateList = QtWidgets.QListWidget(date_window)
        self.DateList.setObjectName("DateList")
        self.gridLayout.addWidget(self.DateList, 3, 0, 1, 3)
        self.line_2 = QtWidgets.QFrame(date_window)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 4, 0, 1, 3)
        self.del_btn = QtWidgets.QPushButton(date_window)
        self.del_btn.setObjectName("del_btn")
        self.gridLayout.addWidget(self.del_btn, 5, 0, 1, 1)
        self.doneButton = QtWidgets.QPushButton(date_window)
        self.doneButton.setObjectName("doneButton")
        self.gridLayout.addWidget(self.doneButton, 5, 1, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(date_window)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 5, 2, 1, 1)

        self.retranslateUi(date_window)
        QtCore.QMetaObject.connectSlotsByName(date_window)

    def retranslateUi(self, date_window):
        _translate = QtCore.QCoreApplication.translate
        date_window.setWindowTitle(_translate("date_window", "Selection Date"))
        self.keyword_label.setText(_translate("date_window", "new keyword"))
        self.date_label.setText(_translate("date_window", "TODAY : "))
        self.label.setText(_translate("date_window", "What\'s date you want to show?"))
        self.select_btn.setText(_translate("date_window", "select all"))
        self.clear_btn.setText(_translate("date_window", "clear all"))
        self.del_btn.setText(_translate("date_window", "Delete Date"))
        self.doneButton.setText(_translate("date_window", "Done"))
        self.cancelButton.setText(_translate("date_window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    date_window = QtWidgets.QWidget()
    ui = Ui_date_window()
    ui.setupUi(date_window)
    date_window.show()
    sys.exit(app.exec_())
