# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'popup_progress.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_popup_progress(object):
    def setupUi(self, popup_progress):
        popup_progress.setObjectName("popup_progress")
        popup_progress.resize(335, 93)
        self.gridLayout = QtWidgets.QGridLayout(popup_progress)
        self.gridLayout.setObjectName("gridLayout")
        self.key_label = QtWidgets.QLabel(popup_progress)
        self.key_label.setStyleSheet("font: 11pt \"Helvetica\";")
        self.key_label.setObjectName("key_label")
        self.gridLayout.addWidget(self.key_label, 0, 0, 1, 1)
        self.progress_label = QtWidgets.QLabel(popup_progress)
        self.progress_label.setObjectName("progress_label")
        self.gridLayout.addWidget(self.progress_label, 0, 1, 1, 1, QtCore.Qt.AlignRight)
        self.progressBar = QtWidgets.QProgressBar(popup_progress)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 2, 0, 1, 2)

        self.retranslateUi(popup_progress)
        QtCore.QMetaObject.connectSlotsByName(popup_progress)

    def retranslateUi(self, popup_progress):
        _translate = QtCore.QCoreApplication.translate
        popup_progress.setWindowTitle(_translate("popup_progress", "Loading"))
        self.key_label.setText(_translate("popup_progress", "Keyword"))
        self.progress_label.setText(_translate("popup_progress", "what is progress doing?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    popup_progress = QtWidgets.QWidget()
    ui = Ui_popup_progress()
    ui.setupUi(popup_progress)
    popup_progress.show()
    sys.exit(app.exec_())
